# Generated by Django 3.2.11 on 2022-01-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('instrument_token', models.CharField(db_index=True, max_length=50)),
                ('exchange_token', models.CharField(db_index=True, max_length=50)),
                ('tradingsymbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('last_price', models.FloatField()),
                ('expiry', models.DateField(default=None)),
                ('strike', models.FloatField()),
                ('tick_size', models.FloatField()),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(db_index=True, max_length=50)),
                ('segment', models.CharField(db_index=True, max_length=50)),
                ('exchange', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
