# Generated by Django 3.2.11 on 2022-01-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_token', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
