# Generated by Django 3.2.11 on 2022-01-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0002_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentlist',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='instrumentlist',
            name='name',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentlist',
            name='strike',
            field=models.FloatField(null=True),
        ),
    ]
