# Generated by Django 3.2.11 on 2022-01-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0002_auto_20220123_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentlist',
            name='for_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrumentlist',
            name='for_strategy',
            field=models.BooleanField(default=False),
        ),
    ]
