# Generated by Django 3.2.11 on 2022-01-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0003_auto_20220123_0412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trackedInstruments',
        ),
    ]
