# Generated by Django 3.2.11 on 2022-01-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0005_historicalpricesday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpricesday',
            old_name='timestamp',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='historicalpricesminute',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
