# Generated by Django 3.2.11 on 2022-01-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0006_auto_20220108_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpricesday',
            name='tracked_instrument',
        ),
        migrations.RemoveField(
            model_name='historicalpricesminute',
            name='tracked_instrument',
        ),
    ]
