# Generated by Django 3.2.11 on 2022-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0007_auto_20220108_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpricesday',
            name='date',
            field=models.DateField(default='2021-12-01'),
            preserve_default=False,
        ),
    ]
