# Generated by Django 3.2.11 on 2022-01-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0008_historicalpricesday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpricesday',
            old_name='date',
            new_name='tradedate',
        ),
    ]
