# Generated by Django 3.2.11 on 2022-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicalTesting', '0009_rename_date_historicalpricesday_tradedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpricesday',
            name='tradedate',
        ),
        migrations.AddField(
            model_name='historicalpricesminute',
            name='tradedate',
            field=models.DateField(default='2021-12-10'),
            preserve_default=False,
        ),
    ]
